name: InstantRec
options:
  bundleIdPrefix: com.instantrec
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
  postGenCommand: pod install

settings:
  PRODUCT_NAME: InstantRec
  SWIFT_VERSION: "5.0"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  InstantRec:
    type: application
    platform: iOS
    sources:
      - path: Sources/instantrec
        name: Sources
        type: group
    dependencies:
      - package: WhisperKit
        product: WhisperKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.instantrec.app
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      "CODE_SIGN_IDENTITY[sdk=iphoneos*]": "iPhone Developer"
      "CODE_SIGN_IDENTITY[sdk=iphonesimulator*]": ""
      PROVISIONING_PROFILE_SPECIFIER: ""
      INFOPLIST_FILE: Sources/instantrec/Info.plist
      INFOPLIST_KEY_NSMicrophoneUsageDescription: "このアプリは音声録音のためにマイクロフォンアクセスが必要です。"
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/whisperkit
    from: 0.8.0